[AWS]
EC2 = { classificacao = "Compute", urls = ["https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/data-protection.html", "https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-key-pairs.html", "https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-security-groups.html"] }
S3 = { classificacao = "Storage", urls = ["https://docs.aws.amazon.com/AmazonS3/latest/userguide/security-best-practices.html", "https://docs.aws.amazon.com/AmazonS3/latest/userguide/privatelink-interface-endpoints.html", "https://docs.aws.amazon.com/AmazonS3/latest/userguide/UsingEncryption.html"] }

[Azure]
Azure_Functions = { classificacao = "Functions", urls = ["https://learn.microsoft.com/en-us/azure/well-architected/service-guides/azure-functions-security", "https://learn.microsoft.com/en-us/azure/azure-functions/security-concepts"] }
Azure_VM = { classificacao = "Compute", urls = ["https://learn.microsoft.com/en-us/security/benchmark/azure/baselines/virtual-machines-windows-virtual-machines-security-baseline", "https://learn.microsoft.com/en-us/azure/security/fundamentals/virtual-machines-overview"] }

[openai]
openai_key = "sua-chave-api-aqui"