[AWS]
classificacoes = [
    "Compute",
    "Storage",
    "Database",
    "Networking",
    "Security",
    "Machine Learning",
    "Analytics",
    "Developer Tools",
    "IoT",
    "Mobile",
    "Game Tech",
    "Blockchain",
    "Business Applications",
    "AR & VR",
    "Quantum Technologies"
]

[Azure]
classificacoes = [
    "Compute",
    "Storage",
    "Database",
    "Networking",
    "Security",
    "AI + Machine Learning",
    "Analytics",
    "Developer Tools",
    "IoT",
    "Mixed Reality",
    "Integration",
    "Management Tools",
    "Media",
    "Web",
    "Migration"
]

[tabela_labels]
PT-BR = { nome_controle = "Nome do Controle", id_controle = "ID do Controle", justificativa = "Justificativa", riscos_mitigados = "Riscos Mitigados", criticidade = "Criticidade", referencias = "Referências" }
EN-US = { nome_controle = "Control Name", id_controle = "Control ID", justificativa = "Justification", riscos_mitigados = "Mitigated Risks", criticidade = "Criticality", referencias = "References" }
ES-ES = { nome_controle = "Nombre del Control", id_controle = "ID del Control", justificativa = "Justificación", riscos_mitigados = "Riesgos Mitigados", criticidade = "Criticidad", referencias = "Referencias" }
